### ISSUE TITLE
Add all data to our database  (Week 5)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#15]
Have a variety of data in the database - around 100 for each use case.

**Comment by skl1m** [comment]
CRUD in NodeJS:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.html

**Comment by skl1m** [comment]
In order to write to tables I created javascript files and in the CLI interface I followed the instructions on this page.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/dynamodb-example-table-read-write-batch.html

Writing and reading items in batch means several items can be written/read to/from a table. 

First, I followed the instructions on how to install CLI https://aws.amazon.com/cli/
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.CLI.html#Tools.CLI.UsingWithDDB
Then I set up the credentials https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html
Then, I followed the link above to write items to my table.

This took several tries, I had several different approaches before I found the best way to write to my table. I could have used the approach to adding it manually via the AWS services, but this is kind of cheating in that it requires no programming.

~ 25 Hours
