### ISSUE TITLE
Make any changes based on user feedback/bugs found (week 12)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#27]
Fix at least 50% of the bugs/recommendations

**Comment by skl1m** [comment]
For the skill the changes I made include:
- Changing the way the skill welcomes the user.
-- Created several ways that the skill could welcome to user because our user testers wanted more versatility when it came to the interaction.
- Made the welcome message shorter, at first we had a long message that invoked the random fact intent, but many complained it was too long. So instead separated the fact intent into its own intent.
- Updated the code to include es6 Javascript that way there is more error handling.

~ 10 Hours
